package:
  name: opencv
  version: 2.4.12

source:
  fn: opencv-2.4.12.zip
  url: https://github.com/Itseez/opencv/archive/2.4.12.tar.gz

build:
  number: 1

requirements:
  build:
   - cmake 3.3.0
   - numpy
   - eigen 3.2.2
   - tbb 4.3_20141023  # [osx]

  run:
   - python
   - numpy
   - tbb 4.3_20141023  # [osx]

test:
  imports:
    - cv2
    - cv2.cv

about:
  home: http://opencv.org/
  license: BSD
